build:
	transcc_winnt -build -target="Desktop_Game_(Glfw3)" main.monkey

build-run:
	transcc_winnt -build -run -target="Desktop_Game_(Glfw3)" main.monkey

update-run:
	transcc_winnt -update -run -target="Desktop_Game_(Glfw3)" main.monkey

linux-build-run:
	transcc_linux -update -run -target="Desktop_Game_(Glfw3)" main.monkey
