win-build:
	rm -rf main.build*
	transcc_winnt -build -target="Desktop_Game_(Glfw3)" main.monkey

win-build-run:
	rm -rf main.build*
	transcc_winnt -build -run -target="Desktop_Game_(Glfw3)" main.monkey

win-update-run:
	transcc_winnt -update -run -target="Desktop_Game_(Glfw3)" main.monkey

linux-build-run:
	rm -rf main.build*
	transcc_linux -build -run -target="Desktop_Game_(Glfw3)" main.monkey

linux-update-run:
	transcc_linux -update -run -target="Desktop_Game_(Glfw3)" main.monkey
